batch_shipyard:
  storage_account_settings: mystorageaccount
global_resources:
  volumes:
    shared_data_volumes:
      nfs:
        container_path: $AZ_BATCH_NODE_SHARED_DIR/nfs # this is not used
        volume_driver: storage_cluster
