credentials:
  batch:
    aad:
      endpoint: https://batch.core.windows.net/
      directory_id: <AAD directory id>  # AAD directory (tenant) id
      application_id: <AAD application id, if using SP login>  # AAD application (client) id
      auth_key: <Auth key for SP login>  # Service Principal authentication key
    account_service_url: https://<myaccount>.<region>.batch.azure.com
    resource_group: my-resource-group
  management:
    aad:
      endpoint: https://management.azure.com/
      directory_id: <AAD directory id>  # AAD directory (tenant) id
      application_id: <AAD application id, if using SP login>  # AAD application (client) id
      auth_key: <Auth key for SP login>  # Service Principal authentication key
    subscription_id: <subscription id>
  storage:
    mystorageaccount:
      account: <storage account name>
      account_key: <storage account key>
      endpoint: core.windows.net
  slurm:
    db_password: <slurm db pass>
